FROM ubuntu:16.04 AS example

COPY . .

RUN apt-get update && apt-get install -y apt-utils apt-transport-https

RUN apt-get install -y whois python3 python3-pip

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

RUN python3 test.py

