FROM debian:stretch-slim AS example

COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y \
    python3 \
    python3-pip

RUN pip3 install -r requirements.txt

COPY . .

RUN python3 test.py
