FROM debian:stretch

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y whois python3 python3-pip

RUN pip3 install -r requirements.txt

COPY . .

ENTRYPOINT ["python3", "test.py"]

CMD ["google.com"]
