FROM python:3.6-alpine AS example

COPY requirements.txt .

# Install build deps, then run `pip install`,
# then remove unneeded build deps all in a single step.
RUN apk add --no-cache jpeg libpng \
    && \
    apk add --no-cache --virtual .build-deps  \
        build-base \
        zlib-dev \
        jpeg-dev \
        libpng-dev \
    && \
        pip3 install -r requirements.txt \
    && \
        apk del .build-deps --force-broken-world

COPY . .

RUN python3 test.py
