FROM alpine:3.9 AS example

COPY requirements.txt .

RUN apk add --no-cache python3 py3-pillow

RUN pip3 install -r requirements.txt

COPY . .

RUN python3 test.py

FROM scratch AS result

COPY --from=example Lenna-blurred.png .